import{S as v,i as a,a as B}from"./assets/vendor-527658dd.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const M=document.querySelector(".form"),l=document.querySelector(".gallery-grid"),g=document.querySelector(".loader"),u=document.querySelector(".js-load-more-btn");let P=new v(".gallery-grid a",{captionsData:"alt"});M.addEventListener("submit",$);u.addEventListener("click",H);let c=1,d,p=0;async function $(i){var o;if(i.preventDefault(),y(),l.innerHTML="",d=i.target.elements.query.value.trim(),h(),!d){l.innerHTML="",a.error({message:"Search field is empty",position:"topRight"});return}try{c=1;const e=await L();if((o=e==null?void 0:e.hits)!=null&&o.length){m(),p=Math.ceil(e.totalHits/15),f(),S(e.hits);return}throw Error("Sorry, there are no images matching your search query. Please try again!")}catch(e){a.info({message:typeof e=="string"?e:"Something went wrong, sorry!",position:"topRight"})}i.target.reset()}async function H(i){var o;h(),b();try{c+=1;const e=await L();if((o=e==null?void 0:e.hits)!=null&&o.length){m(),f(),S(e.hits);const s=document.querySelector(".gallery-card").getBoundingClientRect().height;scrollBy({top:s*2,behavior:"smooth"});return}throw Error("Sorry, there are no images matching your search query. Please try again!")}catch(e){a.info({message:typeof e=="string"?e:"Something went wrong, sorry!",position:"topRight"})}i.target.reset()}function f(){p!==c?y():(b(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}function h(){g.style.display="inline-block"}function m(){g.style.display="none"}function y(){u.classList.remove("hidden")}function b(){u.classList.add("hidden")}async function L(){return(await B.get("https://pixabay.com/api/",{params:{key:"42157668-d969611c6fdd34526589fe987",q:d,image_type:"photo",orientation:"horizontal",safeSearch:!0,page:c,per_page:15}})).data}function S(i){const o=i.map(({webformatURL:e,largeImageURL:s,tags:t,likes:r,views:n,comments:w,downloads:q})=>`<a href="${s}" class="gallery-card">
      <img src="${e}" alt="${t}" >
      <div class="img-details-box">
      <p class="detail-item"><b>Likes:</b> ${r}</p>
      <p class="detail-item"><b>Views:</b> ${n}</p>
      <p class="detail-item"><b>Comments:</b> ${w}</p>
      <p class="detail-item"><b>Downloads:</b> ${q}</p></div>
      </a>`).join("");l.insertAdjacentHTML("beforeend",o),P.refresh()}
//# sourceMappingURL=commonHelpers.js.map
